// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/abilities/[ability].tsx";
import * as $1 from "./routes/abilities/index.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/pokemon/[id].tsx";
import * as $4 from "./routes/pokemon/index.tsx";
import * as $$0 from "./islands/AbilitiesInfos.tsx";
import * as $$1 from "./islands/AbilitiesListe.tsx";
import * as $$2 from "./islands/Hero.tsx";
import * as $$3 from "./islands/PokeInfos.tsx";
import * as $$4 from "./islands/Pokeliste.tsx";

const manifest = {
  routes: {
    "./routes/abilities/[ability].tsx": $0,
    "./routes/abilities/index.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/pokemon/[id].tsx": $3,
    "./routes/pokemon/index.tsx": $4,
  },
  islands: {
    "./islands/AbilitiesInfos.tsx": $$0,
    "./islands/AbilitiesListe.tsx": $$1,
    "./islands/Hero.tsx": $$2,
    "./islands/PokeInfos.tsx": $$3,
    "./islands/Pokeliste.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
